version: '3.8'

services:
  webapi:
    build:
      context: ./Productos
      dockerfile: Productos.Api/Dockerfile
    container_name: webapi
    ports:
      - "5000:80" 
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyDatabase;User=sa;Password=YourPassword;TrustServerCertificate=true;

  angular:
    build:
      context: ./crud_frontend
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "4200:80"
    depends_on:
      - webapi

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "29Mayo1997"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
