services:
  webapi:
    build:
      context: ./Productos
      dockerfile: Productos.Api/Dockerfile
    container_name: webapi
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=ProductosTest;User Id=sa;Password=Password@123;TrustServerCertificate=true;"
    volumes:
      - ./data-protection-keys:/home/app/.aspnet/DataProtection-Keys:rw
    command: >
      sh -c "./wait-for-it.sh db:1433 -- dotnet ef database update && dotnet Productos.Api.dll"

  angular:
    build:
      context: ./crud_frontend
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "4200:80"
    depends_on:
      - webapi

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql:rw
      - ./init-db.sh:/init-db.sh
    command: /bin/bash -c "sleep 30; /init-db.sh && /opt/mssql/bin/sqlservr"

volumes:
  sql_data:
  data-protection-keys:
